# Generated by Django 3.1.2 on 2020-10-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=5, verbose_name='phone number')),
                ('pin', models.CharField(max_length=5, verbose_name='pin')),
                ('valid_until', models.DateTimeField(verbose_name='date until pin is valid')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
